### ISSUE TITLE
Installed the same way as the other mod you linked this in however it does not work

### ISSUE THREAD

**Issue by NuIIVo1d** [Nihility-Shift/ModuleDeconstruct#1]
Install using bepinEx put mod in plugins folder however does not create uninstall levers

**Comment by 18107** [comment]
Do you have the player log available?

This mod only works for the host (the person who started the game), not anyone joining them. If the host deconstructs a module, it becomes a regular module that anyone can install and deconstruct.

**Comment by NuIIVo1d** [comment]
looking at it again I realize I did the source file instead of the dll it does work now 

2nd question what did you use to compile this?

**Comment by 18107** [comment]
Visual Studio

https://discord.com/channels/1180651062550593536/1181822453366919218

https://discord.gg/ufsDWcCE3y

**Comment by NuIIVo1d** [comment]
Thanks for the reply's nice mod btw
