### ISSUE TITLE
How do I use this?

### ISSUE THREAD

**Issue by dracahn** [Nihility-Shift/ModuleDeconstruct#2]
Hello,
I found this mod.  I'm not sure how to use it though.  Is there any instructions on how to get this working?

**Comment by 18107** [comment]
You will need [BepInEx](https://github.com/BepInEx/BepInEx/releases/tag/v5.4.22) to load the mod. More instructions can be found in the [mod releases](https://discord.com/channels/1180651062550593536/1180661574130741259) section of the [Void Crew Modding](https://discord.gg/ufsDWcCE3y) discord server.
